import type { NakshatraInfo } from "./types";

export const NAKSHATRA_DATA: NakshatraInfo[] = [
  {
    id: 1, name: "Ashwini", slug: "ashwini",
    deity: "Ashwini Kumaras", symbol: "Horse's head",
    rashi: "Mesha (Aries)",
    description: "Ashwini is the first nakshatra in Vedic astrology, symbolizing beginnings, speed, and healing. Governed by the Ashwini Kumaras, the divine physicians, it bestows energy, vitality, and pioneering spirit.",
    syllables: ["Chu", "Che", "Cho", "La"],
    qualities: ["energetic", "pioneering", "healing", "swift", "adventurous"],
  },
  {
    id: 2, name: "Bharani", slug: "bharani",
    deity: "Yama", symbol: "Yoni (vulva)",
    rashi: "Mesha (Aries)",
    description: "Bharani nakshatra is ruled by Yama, the god of death and dharma. It represents creativity, transformation, and the cycle of life. Those born under this nakshatra are highly creative, disciplined, and determined.",
    syllables: ["Li", "Lu", "Le", "Lo"],
    qualities: ["creative", "disciplined", "transformative", "artistic", "intense"],
  },
  {
    id: 3, name: "Krittika", slug: "krittika",
    deity: "Agni", symbol: "Flame, razor",
    rashi: "Mesha/Vrishabha",
    description: "Krittika is ruled by Agni, the fire god. This nakshatra brings clarity, courage, and the power to cut through illusion. It is associated with nourishment, purification, and brilliance.",
    syllables: ["A", "I", "U", "E"],
    qualities: ["courageous", "brilliant", "nurturing", "sharp", "protective"],
  },
  {
    id: 4, name: "Rohini", slug: "rohini",
    deity: "Brahma", symbol: "Chariot, ox cart",
    rashi: "Vrishabha (Taurus)",
    description: "Rohini is one of the most auspicious nakshatras, governed by Brahma the creator. It signifies fertility, growth, beauty, and material prosperity. Those with Rohini nakshatra are charming and creative.",
    syllables: ["O", "Va", "Vi", "Vu"],
    qualities: ["beautiful", "fertile", "creative", "prosperous", "charming"],
  },
  {
    id: 5, name: "Mrigashira", slug: "mrigashira",
    deity: "Soma", symbol: "Deer's head",
    rashi: "Vrishabha/Mithuna",
    description: "Mrigashira is the nakshatra of searching and seeking, governed by Soma, the moon god. It signifies gentle curiosity, sensitivity, and the quest for beauty and spiritual fulfillment.",
    syllables: ["Ve", "Vo", "Ka", "Ki"],
    qualities: ["curious", "gentle", "sensitive", "searching", "artistic"],
  },
  {
    id: 6, name: "Ardra", slug: "ardra",
    deity: "Rudra", symbol: "Teardrop, diamond",
    rashi: "Mithuna (Gemini)",
    description: "Ardra means 'the moist one' and is ruled by Rudra, the storm god. This nakshatra brings transformation through destruction and renewal, symbolizing emotional depth and intellectual brilliance.",
    syllables: ["Ku", "Gha", "Na", "Cha"],
    qualities: ["intense", "transformative", "intellectual", "emotional", "powerful"],
  },
  {
    id: 7, name: "Punarvasu", slug: "punarvasu",
    deity: "Aditi", symbol: "Quiver of arrows",
    rashi: "Mithuna/Karka",
    description: "Punarvasu means 'return of the light' and is governed by Aditi, the mother of gods. It signifies renewal, restoration, and the ability to bounce back after hardship with optimism.",
    syllables: ["Ke", "Ko", "Ha", "Hi"],
    qualities: ["optimistic", "restoring", "philosophical", "virtuous", "generous"],
  },
  {
    id: 8, name: "Pushya", slug: "pushya",
    deity: "Brihaspati", symbol: "Lotus, circle",
    rashi: "Karka (Cancer)",
    description: "Pushya is considered the most auspicious nakshatra and is governed by Brihaspati, the guru of gods. It represents nourishment, spiritual wisdom, and the blossoming of good qualities.",
    syllables: ["Hu", "He", "Ho", "Da"],
    qualities: ["nurturing", "wise", "spiritual", "protective", "auspicious"],
  },
  {
    id: 9, name: "Ashlesha", slug: "ashlesha",
    deity: "Sarpa", symbol: "Serpent",
    rashi: "Karka (Cancer)",
    description: "Ashlesha is ruled by the serpent deity and signifies mysticism, depth, and transformative energy. Those born under this nakshatra are intuitive, perceptive, and possess healing abilities.",
    syllables: ["Di", "Du", "De", "Do"],
    qualities: ["mystical", "intuitive", "perceptive", "healing", "transformative"],
  },
  {
    id: 10, name: "Magha", slug: "magha",
    deity: "Pitrs", symbol: "Palanquin",
    rashi: "Simha (Leo)",
    description: "Magha is ruled by the ancestors (Pitrs) and represents honor, royalty, and legacy. Those born under Magha have strong leadership qualities and deep respect for tradition and family.",
    syllables: ["Ma", "Mi", "Mu", "Me"],
    qualities: ["regal", "honorable", "traditional", "leadership", "powerful"],
  },
  {
    id: 11, name: "Purva Phalguni", slug: "purva-phalguni",
    deity: "Bhaga", symbol: "Front legs of couch",
    rashi: "Simha (Leo)",
    description: "Purva Phalguni is governed by Bhaga, the god of prosperity. It represents pleasure, relaxation, and creative expression. Those with this nakshatra are artistic, romantic, and enjoy life's pleasures.",
    syllables: ["Mo", "Ta", "Ti", "Tu"],
    qualities: ["creative", "romantic", "artistic", "luxurious", "pleasure-seeking"],
  },
  {
    id: 12, name: "Uttara Phalguni", slug: "uttara-phalguni",
    deity: "Aryaman", symbol: "Rear legs of couch",
    rashi: "Simha/Kanya",
    description: "Uttara Phalguni is governed by Aryaman, the patron of contracts and friendship. It represents commitment, generosity, and social service. Those born here are reliable and community-minded.",
    syllables: ["Te", "To", "Pa", "Pi"],
    qualities: ["reliable", "generous", "social", "service-oriented", "balanced"],
  },
  {
    id: 13, name: "Hasta", slug: "hasta",
    deity: "Savitar", symbol: "Hand",
    rashi: "Kanya (Virgo)",
    description: "Hasta is ruled by Savitar, the sun god who brings purification. The symbol is a hand, representing skill, craftsmanship, and healing. Those born under Hasta are dexterous and capable.",
    syllables: ["Pu", "Sha", "Na", "Tha"],
    qualities: ["skillful", "healing", "practical", "intelligent", "witty"],
  },
  {
    id: 14, name: "Chitra", slug: "chitra",
    deity: "Vishvakarma", symbol: "Bright jewel, pearl",
    rashi: "Kanya/Tula",
    description: "Chitra is ruled by Vishvakarma, the divine architect. It represents brilliance, artistry, and the creation of beautiful things. Those born under this nakshatra are creative, glamorous, and refined.",
    syllables: ["Pe", "Po", "Ra", "Ri"],
    qualities: ["artistic", "creative", "glamorous", "refined", "intelligent"],
  },
  {
    id: 15, name: "Swati", slug: "swati",
    deity: "Vayu", symbol: "Coral, sword",
    rashi: "Tula (Libra)",
    description: "Swati is governed by Vayu, the god of wind. It signifies independence, movement, and freedom. Those born under Swati are flexible, diplomatic, and naturally inclined toward business.",
    syllables: ["Ru", "Re", "Ro", "Ta"],
    qualities: ["independent", "flexible", "diplomatic", "business-minded", "adaptable"],
  },
  {
    id: 16, name: "Vishakha", slug: "vishakha",
    deity: "Indra-Agni", symbol: "Triumphal arch",
    rashi: "Tula/Vrishchika",
    description: "Vishakha is jointly governed by Indra and Agni, signifying power and passion. It represents ambitious goals, determination, and the drive to succeed. Those born here are single-minded achievers.",
    syllables: ["Ti", "Tu", "Te", "To"],
    qualities: ["ambitious", "determined", "passionate", "goal-oriented", "powerful"],
  },
  {
    id: 17, name: "Anuradha", slug: "anuradha",
    deity: "Mitra", symbol: "Lotus, staff",
    rashi: "Vrishchika (Scorpio)",
    description: "Anuradha is ruled by Mitra, the god of friendship and cooperation. It represents friendship, devotion, and spiritual discipline. Those born here are loyal, devoted, and have excellent organizational skills.",
    syllables: ["Na", "Ni", "Nu", "Ne"],
    qualities: ["devoted", "friendly", "disciplined", "organized", "loyal"],
  },
  {
    id: 18, name: "Jyeshtha", slug: "jyeshtha",
    deity: "Indra", symbol: "Circular amulet, earring",
    rashi: "Vrishchika (Scorpio)",
    description: "Jyeshtha means 'the eldest' and is governed by Indra, the king of gods. It represents seniority, authority, and protective power. Those born under Jyeshtha are natural leaders with strong protective instincts.",
    syllables: ["No", "Ya", "Yi", "Yu"],
    qualities: ["authoritative", "protective", "senior", "powerful", "responsible"],
  },
  {
    id: 19, name: "Mula", slug: "mula",
    deity: "Nirriti", symbol: "Bunch of roots, tail of lion",
    rashi: "Dhanu (Sagittarius)",
    description: "Mula means 'root' and is governed by Nirriti, the goddess of dissolution. It represents the urge to get to the root of things, research, and fundamental truths. Mula nakshatra people are philosophical and investigative.",
    syllables: ["Ye", "Yo", "Ba", "Bi"],
    qualities: ["investigative", "philosophical", "determined", "fundamental", "spiritual"],
  },
  {
    id: 20, name: "Purva Ashadha", slug: "purva-ashadha",
    deity: "Apas", symbol: "Elephant tusk, fan",
    rashi: "Dhanu (Sagittarius)",
    description: "Purva Ashadha is governed by Apas, the water goddess. It signifies invincibility, purification, and early victory. Those born here are energetic, philosophical, and have a strong sense of justice.",
    syllables: ["Bu", "Dha", "Bha", "Pha"],
    qualities: ["invincible", "philosophical", "just", "energetic", "purifying"],
  },
  {
    id: 21, name: "Uttara Ashadha", slug: "uttara-ashadha",
    deity: "Vishvedevas", symbol: "Elephant tusk, small bed",
    rashi: "Dhanu/Makara",
    description: "Uttara Ashadha is governed by the Vishvedevas, the universal gods. It represents final victory, righteousness, and unstoppable success. Those born here are sincere, principled, and achieve lasting success.",
    syllables: ["Be", "Bo", "Ja", "Ji"],
    qualities: ["righteous", "victorious", "sincere", "principled", "persistent"],
  },
  {
    id: 22, name: "Shravana", slug: "shravana",
    deity: "Vishnu", symbol: "Ear, three footprints",
    rashi: "Makara (Capricorn)",
    description: "Shravana means 'hearing' and is governed by Vishnu, the preserver. It represents learning, listening, and spreading knowledge. Those born under Shravana are good listeners, learned, and skilled communicators.",
    syllables: ["Ju", "Je", "Jo", "Gha"],
    qualities: ["learned", "listening", "knowledgeable", "communicative", "organized"],
  },
  {
    id: 23, name: "Dhanishta", slug: "dhanishta",
    deity: "Vasus", symbol: "Drum, flute",
    rashi: "Makara/Kumbha",
    description: "Dhanishta means 'richest' and is governed by the Vasus. It represents wealth, music, and abundance. Those born under this nakshatra are musically talented, socially adaptable, and attract prosperity.",
    syllables: ["Ga", "Gi", "Gu", "Ge"],
    qualities: ["wealthy", "musical", "adaptable", "abundant", "sociable"],
  },
  {
    id: 24, name: "Shatabhisha", slug: "shatabhisha",
    deity: "Varuna", symbol: "Empty circle, 1000 flowers",
    rashi: "Kumbha (Aquarius)",
    description: "Shatabhisha means 'a hundred healers' and is governed by Varuna, the cosmic law enforcer. It represents healing, mysticism, and independence. Those born here are healers, researchers, and truth-seekers.",
    syllables: ["Go", "Sa", "Si", "Su"],
    qualities: ["healing", "mystical", "independent", "research-oriented", "visionary"],
  },
  {
    id: 25, name: "Purva Bhadrapada", slug: "purva-bhadrapada",
    deity: "Ajaikapada", symbol: "Sword, two front legs of funeral cot",
    rashi: "Kumbha/Meena",
    description: "Purva Bhadrapada is governed by Ajaikapada, a form of Rudra. It represents intense passion, spirituality, and transformation. Those born here are idealistic, passionate, and spiritually inclined.",
    syllables: ["Se", "So", "Da", "Di"],
    qualities: ["passionate", "spiritual", "transformative", "idealistic", "intense"],
  },
  {
    id: 26, name: "Uttara Bhadrapada", slug: "uttara-bhadrapada",
    deity: "Ahirbudhnya", symbol: "Twins, back legs of funeral cot",
    rashi: "Meena (Pisces)",
    description: "Uttara Bhadrapada is governed by Ahirbudhnya, the serpent of the deep. It represents depth, wisdom, and spiritual mastery. Those born here are wise, philanthropic, and deeply compassionate.",
    syllables: ["Du", "Tha", "Jha", "Da"],
    qualities: ["wise", "compassionate", "spiritual", "philanthropic", "deep"],
  },
  {
    id: 27, name: "Revati", slug: "revati",
    deity: "Pushan", symbol: "Fish, drum",
    rashi: "Meena (Pisces)",
    description: "Revati is the final nakshatra, governed by Pushan, the nourisher. It represents completion, prosperity, and spiritual fulfillment. Those born under Revati are nurturing, creative, and spiritually advanced.",
    syllables: ["De", "Do", "Cha", "Chi"],
    qualities: ["nurturing", "creative", "spiritual", "prosperous", "compassionate"],
  },
];

export function getNakshatraBySlug(slug: string): NakshatraInfo | undefined {
  return NAKSHATRA_DATA.find((n) => n.slug === slug);
}

export function getNakshatraByName(name: string): NakshatraInfo | undefined {
  return NAKSHATRA_DATA.find(
    (n) => n.name.toLowerCase() === name.toLowerCase()
  );
}
