/**
 * Vedic Astrology Utility — Nakshatra Baby Names Platform
 *
 * Provides high-precision Nakshatra, Rashi, and Pada calculation using:
 * - astronomy-engine (ELP/MPP02 lunar theory) for Moon's tropical longitude
 * - B.V. Raman Ayanamsa (traditional South Indian standard)
 *
 * This is the canonical astrology utility for the platform.
 * All calculation logic lives here.
 */

export {
  calculateNakshatra,
  type NakshatraResult,
} from "./nakshatraCalculator";

import { NAKSHATRA_DATA } from "@/lib/nakshatraData";

// ─── Result Page ID Utilities ──────────────────────────────────────────────

/**
 * Build the result page URL segment from nakshatra name + pada.
 * Format: `{slug}-pada-{pada}` e.g., `rohini-pada-3`
 */
export function buildResultId(nakshatraName: string, pada: number): string {
  const slug = nakshatraName.toLowerCase().replace(/\s+/g, "-");
  return `${slug}-pada-${pada}`;
}

/**
 * Parse a result page ID back into nakshatra slug + pada.
 * Returns null if the ID is invalid.
 */
export function parseResultId(
  id: string
): { slug: string; pada: number } | null {
  const match = id.match(/^(.+)-pada-([1-4])$/);
  if (!match) return null;
  return { slug: match[1], pada: parseInt(match[2], 10) };
}

/**
 * Generate all valid result page IDs (108 total: 27 nakshatras × 4 padas).
 */
export function getAllResultIds(): { id: string }[] {
  const ids: { id: string }[] = [];
  for (const nk of NAKSHATRA_DATA) {
    for (let pada = 1; pada <= 4; pada++) {
      ids.push({ id: buildResultId(nk.name, pada) });
    }
  }
  return ids;
}

// ─── Nakshatra Personality Data ────────────────────────────────────────────

export interface NakshatraPersonality {
  nakshatraSlug: string;
  nakshatraName: string;
  element: string;
  planetaryRuler: string;
  gana: "Deva" | "Manushya" | "Rakshasa";
  nature: string;
  personalities: string[];
  strengths: string[];
  weaknesses: string[];
  luckyColors: string[];
  luckyNumbers: number[];
  luckyGems: string[];
  luckyDays: string[];
  careerPaths: string[];
  compatibleNakshatras: string[];
  lifeTheme: string;
  padaThemes: {
    pada: number;
    theme: string;
    qualities: string[];
  }[];
}

export const NAKSHATRA_PERSONALITIES: NakshatraPersonality[] = [
  {
    nakshatraSlug: "ashwini",
    nakshatraName: "Ashwini",
    element: "Earth",
    planetaryRuler: "Ketu",
    gana: "Deva",
    nature: "Kshipra (Swift)",
    personalities: [
      "Dynamic and energetic with an innate healing instinct",
      "Pioneering spirit — loves being first and setting trends",
      "Quick thinker who makes decisions with confidence",
      "Naturally athletic and physically active",
      "Charming and magnetic social presence",
      "Impatient at times, prefers action over deliberation",
    ],
    strengths: [
      "Natural leader and pioneer",
      "Excellent healing and helping instincts",
      "High physical energy and vitality",
      "Quick learner who adapts rapidly",
      "Inspiring and motivating to others",
    ],
    weaknesses: [
      "Can be impulsive and rush into decisions",
      "May become restless when routine sets in",
      "Stubbornness when challenged",
    ],
    luckyColors: ["Red", "Crimson", "Orange"],
    luckyNumbers: [1, 9],
    luckyGems: ["Ruby", "Coral"],
    luckyDays: ["Tuesday", "Sunday"],
    careerPaths: ["Medicine", "Sports", "Military", "Entrepreneurship", "Healing arts"],
    compatibleNakshatras: ["Shatabhisha", "Swati", "Punarvasu", "Pushya"],
    lifeTheme: "Initiation, healing, and pioneering new frontiers",
    padaThemes: [
      { pada: 1, theme: "Aries energy — bold, direct, leadership-focused", qualities: ["Chu", "initiative", "warrior spirit"] },
      { pada: 2, theme: "Taurus sub-influence — material security, beauty", qualities: ["Che", "aesthetic sense", "persistence"] },
      { pada: 3, theme: "Gemini sub-influence — communication, curiosity", qualities: ["Cho", "intellectual spark", "versatility"] },
      { pada: 4, theme: "Cancer sub-influence — nurturing, emotional depth", qualities: ["La", "compassion", "intuition"] },
    ],
  },
  {
    nakshatraSlug: "bharani",
    nakshatraName: "Bharani",
    element: "Earth",
    planetaryRuler: "Venus",
    gana: "Manushya",
    nature: "Ugra (Fierce/Severe)",
    personalities: [
      "Deeply creative with strong artistic talents",
      "Determined and disciplined — finishes what they start",
      "Passionate and intense in all pursuits",
      "Strong sense of justice and dharmic principles",
      "Protective of family and loved ones",
      "Can carry burdens gracefully due to inner strength",
    ],
    strengths: [
      "Extraordinary creativity and artistic expression",
      "Tremendous willpower and resilience",
      "Deep loyalty to family and principles",
      "Ability to handle life's transformations",
      "Natural talent for managing responsibilities",
    ],
    weaknesses: [
      "Can be overly intense or obsessive",
      "May struggle with letting go of the past",
      "Tendency toward stubbornness",
    ],
    luckyColors: ["Pink", "Rose", "White"],
    luckyNumbers: [2, 6],
    luckyGems: ["Diamond", "White Sapphire"],
    luckyDays: ["Friday", "Wednesday"],
    careerPaths: ["Arts", "Music", "Management", "Law", "Psychology"],
    compatibleNakshatras: ["Rohini", "Hasta", "Purva Phalguni", "Uttara Phalguni"],
    lifeTheme: "Creation, transformation, and embracing life's full spectrum",
    padaThemes: [
      { pada: 1, theme: "Aries energy — courage, initiative, raw vitality", qualities: ["Li", "courage", "assertiveness"] },
      { pada: 2, theme: "Taurus sub-influence — sensual beauty, luxury", qualities: ["Lu", "artistic eye", "material comfort"] },
      { pada: 3, theme: "Gemini sub-influence — intellectual creativity", qualities: ["Le", "communication", "wit"] },
      { pada: 4, theme: "Cancer sub-influence — deep emotional nature", qualities: ["Lo", "nurturing", "sensitivity"] },
    ],
  },
  {
    nakshatraSlug: "krittika",
    nakshatraName: "Krittika",
    element: "Earth/Fire",
    planetaryRuler: "Sun",
    gana: "Rakshasa",
    nature: "Tikshna (Sharp/Dreadful)",
    personalities: [
      "Sharp intellect with great powers of discernment",
      "Natural protector — stands up for truth and justice",
      "Purifying energy that burns away the unnecessary",
      "Courageous with a warrior's spirit",
      "Nurturing when protective instincts are engaged",
      "High standards for self and others",
    ],
    strengths: [
      "Sharp intellect and critical thinking",
      "Courage to face difficult truths",
      "Natural authority and leadership presence",
      "Strong protective instincts",
      "Ability to cut through confusion to core truth",
    ],
    weaknesses: [
      "Can be harsh or overly critical",
      "Perfectionist tendencies cause frustration",
      "May struggle with flexibility",
    ],
    luckyColors: ["Gold", "Yellow", "White"],
    luckyNumbers: [1, 4],
    luckyGems: ["Ruby", "Yellow Sapphire"],
    luckyDays: ["Sunday", "Thursday"],
    careerPaths: ["Military", "Surgery", "Law", "Teaching", "Leadership"],
    compatibleNakshatras: ["Ashwini", "Pushya", "Magha", "Uttara Phalguni"],
    lifeTheme: "Purification, courage, and illuminating truth",
    padaThemes: [
      { pada: 1, theme: "Aries energy — fiery courage and independence", qualities: ["A", "boldness", "leadership"] },
      { pada: 2, theme: "Taurus sub-influence — steady, nurturing warmth", qualities: ["I", "stability", "abundance"] },
      { pada: 3, theme: "Gemini sub-influence — sharp communication", qualities: ["U", "intelligence", "curiosity"] },
      { pada: 4, theme: "Cancer sub-influence — protective nurturing", qualities: ["E", "care", "home"] },
    ],
  },
  {
    nakshatraSlug: "rohini",
    nakshatraName: "Rohini",
    element: "Earth",
    planetaryRuler: "Moon",
    gana: "Manushya",
    nature: "Sthira (Fixed)",
    personalities: [
      "Naturally beautiful with magnetic charm",
      "Creative mind with appreciation for fine things",
      "Deeply fertile imagination — prolific creators",
      "Romantic and passionate in relationships",
      "Strong connection to nature and the material world",
      "Nurturing and growth-oriented in all endeavors",
    ],
    strengths: [
      "Natural beauty, grace, and artistic talent",
      "Magnetic charisma and social appeal",
      "Excellent creative and productive abilities",
      "Deep nurturing and caring nature",
      "Material prosperity often follows naturally",
    ],
    weaknesses: [
      "Can be possessive or materially attached",
      "Tendency toward indulgence",
      "May become obstinate once mind is set",
    ],
    luckyColors: ["White", "Cream", "Light Green"],
    luckyNumbers: [2, 4],
    luckyGems: ["Pearl", "Moonstone"],
    luckyDays: ["Monday", "Friday"],
    careerPaths: ["Arts", "Agriculture", "Design", "Finance", "Hospitality"],
    compatibleNakshatras: ["Mrigashira", "Hasta", "Uttara Phalguni", "Vishakha"],
    lifeTheme: "Beauty, growth, creation, and abundant flowering of life",
    padaThemes: [
      { pada: 1, theme: "Aries sub-influence — creative initiative and passion", qualities: ["O", "creative fire", "determination"] },
      { pada: 2, theme: "Taurus sub-influence — sensual beauty, stability", qualities: ["Va", "beauty", "prosperity"] },
      { pada: 3, theme: "Gemini sub-influence — artistic communication", qualities: ["Vi", "expression", "versatility"] },
      { pada: 4, theme: "Cancer sub-influence — deep emotional nurturing", qualities: ["Vu", "love", "home"] },
    ],
  },
  {
    nakshatraSlug: "mrigashira",
    nakshatraName: "Mrigashira",
    element: "Earth/Air",
    planetaryRuler: "Mars",
    gana: "Deva",
    nature: "Mridu (Soft/Tender)",
    personalities: [
      "Eternally curious and seeking",
      "Gentle and sensitive with artistic sensibility",
      "Quick-witted with sharp observational skills",
      "Romantic idealist who searches for perfection",
      "Adaptable and flexible in changing circumstances",
      "Deep love of beauty, nature, and aesthetics",
    ],
    strengths: [
      "Intellectual curiosity and love of learning",
      "Gentle, sensitive communication style",
      "Artistic talent and aesthetic appreciation",
      "Adaptability and social intelligence",
      "Romantic and idealistic heart",
    ],
    weaknesses: [
      "Can be restless and perpetually searching",
      "May scatter energy across too many interests",
      "Indecisiveness when seeking perfection",
    ],
    luckyColors: ["Green", "Olive", "Light Blue"],
    luckyNumbers: [3, 5],
    luckyGems: ["Emerald", "Jade"],
    luckyDays: ["Wednesday", "Thursday"],
    careerPaths: ["Research", "Writing", "Travel", "Arts", "Teaching"],
    compatibleNakshatras: ["Chitra", "Punarvasu", "Rohini", "Revati"],
    lifeTheme: "Eternal searching, gentle discovery, and the quest for beauty",
    padaThemes: [
      { pada: 1, theme: "Taurus energy — grounded, sensual exploration", qualities: ["Ve", "beauty", "stability"] },
      { pada: 2, theme: "Taurus sub-influence — material comfort", qualities: ["Vo", "prosperity", "artistry"] },
      { pada: 3, theme: "Gemini sub-influence — intellectual restlessness", qualities: ["Ka", "curiosity", "communication"] },
      { pada: 4, theme: "Gemini sub-influence — social and communicative", qualities: ["Ki", "versatility", "wit"] },
    ],
  },
  {
    nakshatraSlug: "ardra",
    nakshatraName: "Ardra",
    element: "Water/Air",
    planetaryRuler: "Rahu",
    gana: "Manushya",
    nature: "Tikshna (Sharp)",
    personalities: [
      "Intellectually brilliant with penetrating insight",
      "Emotionally intense and deeply feeling",
      "Transformative — thrives in periods of change",
      "Unconventional thinker who questions everything",
      "Compassionate heart beneath a tough exterior",
      "Strong willpower forged through life's storms",
    ],
    strengths: [
      "Brilliant and penetrating intellect",
      "Great empathy and emotional understanding",
      "Ability to thrive through transformation",
      "Creative problem-solving under pressure",
      "Passionate and determined pursuer of goals",
    ],
    weaknesses: [
      "Emotional turbulence and mood swings",
      "Can be destructive when frustrated",
      "Restlessness and dissatisfaction with status quo",
    ],
    luckyColors: ["Blue", "Electric Blue", "Silver"],
    luckyNumbers: [4, 9],
    luckyGems: ["Hessonite (Gomed)", "Blue Sapphire"],
    luckyDays: ["Saturday", "Wednesday"],
    careerPaths: ["Research", "Philosophy", "Technology", "Psychology", "Social reform"],
    compatibleNakshatras: ["Punarvasu", "Jyeshtha", "Dhanishta", "Purva Bhadrapada"],
    lifeTheme: "Transformation through storms, renewal through destruction",
    padaThemes: [
      { pada: 1, theme: "Gemini energy — intellectual transformation", qualities: ["Ku", "brilliance", "curiosity"] },
      { pada: 2, theme: "Gemini sub-influence — communicative depth", qualities: ["Gha", "expression", "insight"] },
      { pada: 3, theme: "Gemini sub-influence — analytical power", qualities: ["Ng", "analysis", "transformation"] },
      { pada: 4, theme: "Gemini sub-influence — deep questioning mind", qualities: ["Na", "depth", "wisdom"] },
    ],
  },
  {
    nakshatraSlug: "punarvasu",
    nakshatraName: "Punarvasu",
    element: "Water",
    planetaryRuler: "Jupiter",
    gana: "Deva",
    nature: "Chara (Movable)",
    personalities: [
      "Optimistic and resilient — always bounces back",
      "Philosophical mind with genuine wisdom",
      "Generous and virtuous with a giving heart",
      "Excellent at restoring and healing broken things",
      "Spiritual inclination and interest in higher truths",
      "Good-humored and joyful even through hardships",
    ],
    strengths: [
      "Remarkable resilience and optimism",
      "Genuine wisdom and philosophical insight",
      "Generosity and natural virtue",
      "Healing and restorative abilities",
      "Joy and humor that uplifts others",
    ],
    weaknesses: [
      "Can be naive or overly trusting",
      "May overextend generosity",
      "Tendency to idealize people",
    ],
    luckyColors: ["Yellow", "Gold", "Cream"],
    luckyNumbers: [3, 9],
    luckyGems: ["Yellow Sapphire", "Topaz"],
    luckyDays: ["Thursday", "Monday"],
    careerPaths: ["Teaching", "Counseling", "Philosophy", "Medicine", "Spirituality"],
    compatibleNakshatras: ["Ashwini", "Vishakha", "Uttara Bhadrapada", "Revati"],
    lifeTheme: "Return to goodness, renewal of hope, and restoration of light",
    padaThemes: [
      { pada: 1, theme: "Aries energy — optimistic leadership", qualities: ["Ke", "enthusiasm", "initiative"] },
      { pada: 2, theme: "Taurus sub-influence — steady restoration", qualities: ["Ko", "persistence", "beauty"] },
      { pada: 3, theme: "Gemini sub-influence — intellectual wisdom", qualities: ["Ha", "communication", "teaching"] },
      { pada: 4, theme: "Cancer sub-influence — nurturing wisdom", qualities: ["Hi", "compassion", "healing"] },
    ],
  },
  {
    nakshatraSlug: "pushya",
    nakshatraName: "Pushya",
    element: "Water",
    planetaryRuler: "Saturn",
    gana: "Deva",
    nature: "Laghu (Light/Swift)",
    personalities: [
      "Deeply nurturing and protective of loved ones",
      "Spiritually evolved with genuine wisdom",
      "Patient and disciplined in all endeavors",
      "Excellent at nourishing and cultivating growth",
      "Reliable and steady — the rock of any family",
      "Naturally auspicious energy that blesses gatherings",
    ],
    strengths: [
      "Extraordinary nurturing and caring instincts",
      "Spiritual wisdom and devotion",
      "Patient, disciplined, long-term thinking",
      "Ability to protect and provide for others",
      "Natural auspiciousness in all undertakings",
    ],
    weaknesses: [
      "Can be overly protective or possessive",
      "May sacrifice own needs excessively",
      "Tendency toward rigidity in tradition",
    ],
    luckyColors: ["Red", "Orange", "Saffron"],
    luckyNumbers: [2, 7],
    luckyGems: ["Blue Sapphire", "Amethyst"],
    luckyDays: ["Saturday", "Monday"],
    careerPaths: ["Education", "Social work", "Medicine", "Agriculture", "Spirituality"],
    compatibleNakshatras: ["Rohini", "Krittika", "Hasta", "Anuradha"],
    lifeTheme: "Nourishment, spiritual grace, and the flowering of goodness",
    padaThemes: [
      { pada: 1, theme: "Cancer energy — deep emotional nurturing", qualities: ["Hu", "care", "protection"] },
      { pada: 2, theme: "Leo sub-influence — generous heart and dignity", qualities: ["He", "nobility", "warmth"] },
      { pada: 3, theme: "Virgo sub-influence — service and precision", qualities: ["Ho", "service", "detail"] },
      { pada: 4, theme: "Libra sub-influence — balanced nourishment", qualities: ["Da", "harmony", "justice"] },
    ],
  },
  {
    nakshatraSlug: "ashlesha",
    nakshatraName: "Ashlesha",
    element: "Water",
    planetaryRuler: "Mercury",
    gana: "Rakshasa",
    nature: "Tikshna (Sharp)",
    personalities: [
      "Deeply intuitive and perceptive beyond the obvious",
      "Magnetic and mesmerizing personality",
      "Healing abilities especially in esoteric fields",
      "Sharp mind that perceives hidden motives",
      "Intense and passionate in all relationships",
      "Transformative energy that sheds old skin for new growth",
    ],
    strengths: [
      "Extraordinary intuition and psychic sensitivity",
      "Healing abilities in both physical and emotional realms",
      "Magnetic personality that draws people in",
      "Penetrating intelligence",
      "Transformative power to heal and regenerate",
    ],
    weaknesses: [
      "Can be manipulative when insecure",
      "Secretive and emotionally guarded",
      "Intensity can overwhelm others",
    ],
    luckyColors: ["Green", "Grey", "Silver"],
    luckyNumbers: [5, 6],
    luckyGems: ["Emerald", "Green Tourmaline"],
    luckyDays: ["Wednesday", "Monday"],
    careerPaths: ["Healing", "Psychology", "Research", "Mysticism", "Medicine"],
    compatibleNakshatras: ["Jyeshtha", "Pushya", "Ardra", "Purva Bhadrapada"],
    lifeTheme: "Deep healing, transformation through wisdom, and mystical understanding",
    padaThemes: [
      { pada: 1, theme: "Cancer energy — deep emotional perception", qualities: ["Di", "intuition", "healing"] },
      { pada: 2, theme: "Leo sub-influence — magnetic dignity", qualities: ["Du", "charisma", "strength"] },
      { pada: 3, theme: "Virgo sub-influence — analytical healing", qualities: ["De", "precision", "wisdom"] },
      { pada: 4, theme: "Libra sub-influence — balanced transformation", qualities: ["Do", "harmony", "justice"] },
    ],
  },
  {
    nakshatraSlug: "magha",
    nakshatraName: "Magha",
    element: "Fire",
    planetaryRuler: "Ketu",
    gana: "Rakshasa",
    nature: "Ugra (Fierce)",
    personalities: [
      "Regal bearing and natural authority that commands respect",
      "Deep respect for tradition and ancestral wisdom",
      "Strong leadership qualities from a young age",
      "Generous patron who honors and supports others",
      "Pride in heritage and cultural identity",
      "Powerful executive abilities and organizational skills",
    ],
    strengths: [
      "Natural authority and leadership presence",
      "Deep respect for lineage and tradition",
      "Generosity and patron qualities",
      "Executive organizational abilities",
      "Power and dignity in all pursuits",
    ],
    weaknesses: [
      "Can be arrogant or overly proud",
      "May be too attached to tradition",
      "Difficulty accepting criticism",
    ],
    luckyColors: ["Gold", "Crimson", "Dark Red"],
    luckyNumbers: [1, 9],
    luckyGems: ["Ruby", "Garnet"],
    luckyDays: ["Sunday", "Tuesday"],
    careerPaths: ["Politics", "Leadership", "Royalty", "Business", "Cultural arts"],
    compatibleNakshatras: ["Uttara Phalguni", "Vishakha", "Jyeshtha", "Purva Phalguni"],
    lifeTheme: "Royal legacy, ancestral honor, and dignified leadership",
    padaThemes: [
      { pada: 1, theme: "Leo energy — regal leadership and authority", qualities: ["Ma", "royalty", "command"] },
      { pada: 2, theme: "Virgo sub-influence — precise administration", qualities: ["Mi", "organization", "service"] },
      { pada: 3, theme: "Libra sub-influence — just and balanced rule", qualities: ["Mu", "balance", "justice"] },
      { pada: 4, theme: "Scorpio sub-influence — deep ancestral power", qualities: ["Me", "depth", "legacy"] },
    ],
  },
  {
    nakshatraSlug: "purva-phalguni",
    nakshatraName: "Purva Phalguni",
    element: "Fire",
    planetaryRuler: "Venus",
    gana: "Manushya",
    nature: "Ugra (Fierce)",
    personalities: [
      "Creative, artistic, and naturally talented",
      "Romantic with deep appreciation for beauty",
      "Joyful and pleasure-loving with generous spirit",
      "Magnetic and socially gifted",
      "Supportive and loyal in relationships",
      "Natural performer and entertainer",
    ],
    strengths: [
      "Exceptional creative and artistic abilities",
      "Magnetic charm and social grace",
      "Deep generosity and loyalty",
      "Natural talent for performance and expression",
      "Joy-bringing presence in all gatherings",
    ],
    weaknesses: [
      "Can be self-indulgent or lazy",
      "May avoid responsibilities",
      "Tendency toward vanity",
    ],
    luckyColors: ["Pink", "Rose", "Lavender"],
    luckyNumbers: [2, 6],
    luckyGems: ["Diamond", "Opal"],
    luckyDays: ["Friday", "Wednesday"],
    careerPaths: ["Arts", "Entertainment", "Fashion", "Hospitality", "Relationships"],
    compatibleNakshatras: ["Bharani", "Uttara Phalguni", "Rohini", "Magha"],
    lifeTheme: "Joy, creativity, love, and the pleasures of artistic life",
    padaThemes: [
      { pada: 1, theme: "Leo energy — creative performance and joy", qualities: ["Mo", "artistry", "joy"] },
      { pada: 2, theme: "Virgo sub-influence — refined artistic skill", qualities: ["Ta", "craft", "beauty"] },
      { pada: 3, theme: "Libra sub-influence — balanced aesthetics", qualities: ["Ti", "harmony", "grace"] },
      { pada: 4, theme: "Scorpio sub-influence — passionate depth", qualities: ["Tu", "intensity", "loyalty"] },
    ],
  },
  {
    nakshatraSlug: "uttara-phalguni",
    nakshatraName: "Uttara Phalguni",
    element: "Fire",
    planetaryRuler: "Sun",
    gana: "Manushya",
    nature: "Sthira (Fixed)",
    personalities: [
      "Reliable and committed — a person of their word",
      "Generous with resources and abilities",
      "Strong social conscience and service orientation",
      "Gifted in forming and maintaining relationships",
      "Natural counselor and confidant",
      "Steady and grounded with long-term vision",
    ],
    strengths: [
      "Exceptional reliability and trustworthiness",
      "Generosity and community spirit",
      "Strong relationship and counseling skills",
      "Steady character and long-term vision",
      "Natural peacemaker and mediator",
    ],
    weaknesses: [
      "Can be overly dependent on others",
      "May struggle with being alone",
      "Tendency to overcommit",
    ],
    luckyColors: ["Orange", "Gold", "White"],
    luckyNumbers: [1, 5],
    luckyGems: ["Ruby", "Sunstone"],
    luckyDays: ["Sunday", "Thursday"],
    careerPaths: ["Social work", "Counseling", "Education", "Business", "Governance"],
    compatibleNakshatras: ["Purva Phalguni", "Swati", "Vishakha", "Hasta"],
    lifeTheme: "Service, reliability, generous partnerships, and social harmony",
    padaThemes: [
      { pada: 1, theme: "Leo energy — generous leadership", qualities: ["Te", "leadership", "generosity"] },
      { pada: 2, theme: "Virgo sub-influence — service-oriented", qualities: ["To", "service", "skill"] },
      { pada: 3, theme: "Virgo sub-influence — analytical care", qualities: ["Pa", "precision", "dedication"] },
      { pada: 4, theme: "Virgo sub-influence — detailed nurturing", qualities: ["Pi", "detail", "commitment"] },
    ],
  },
  {
    nakshatraSlug: "hasta",
    nakshatraName: "Hasta",
    element: "Earth",
    planetaryRuler: "Moon",
    gana: "Deva",
    nature: "Kshipra (Swift)",
    personalities: [
      "Highly skilled with exceptional manual dexterity",
      "Sharp wit and excellent sense of humor",
      "Practical problem-solver with hands-on approach",
      "Helpful and service-oriented by nature",
      "Intelligent and adaptable in any situation",
      "Playful yet disciplined",
    ],
    strengths: [
      "Exceptional manual and practical skills",
      "Sharp intelligence and wit",
      "Service orientation and helpfulness",
      "Adaptability and quick learning",
      "Humor and lightheartedness",
    ],
    weaknesses: [
      "Can be cunning or deceptive when cornered",
      "May be overly restless",
      "Tendency to gossip",
    ],
    luckyColors: ["Green", "Blue-Green", "Teal"],
    luckyNumbers: [2, 6],
    luckyGems: ["Pearl", "Green Emerald"],
    luckyDays: ["Monday", "Wednesday"],
    careerPaths: ["Crafts", "Healing", "Comedy", "Trade", "Service industries"],
    compatibleNakshatras: ["Ashwini", "Pushya", "Shravana", "Uttara Bhadrapada"],
    lifeTheme: "Skillful service, practical mastery, and joyful contribution",
    padaThemes: [
      { pada: 1, theme: "Aries energy — skilled initiative", qualities: ["Pu", "skill", "initiative"] },
      { pada: 2, theme: "Taurus sub-influence — crafted beauty", qualities: ["Sha", "artistry", "beauty"] },
      { pada: 3, theme: "Gemini sub-influence — clever communication", qualities: ["Na", "wit", "versatility"] },
      { pada: 4, theme: "Cancer sub-influence — nurturing skills", qualities: ["Tha", "healing", "care"] },
    ],
  },
  {
    nakshatraSlug: "chitra",
    nakshatraName: "Chitra",
    element: "Fire",
    planetaryRuler: "Mars",
    gana: "Rakshasa",
    nature: "Mridu (Soft)",
    personalities: [
      "Brilliant creative vision and artistic genius",
      "Glamorous presence with natural refinement",
      "Architectural mind — sees how things fit together",
      "Perfectionist with an eye for beauty and detail",
      "Magnetic and attractive to others",
      "Innovative and original in approach",
    ],
    strengths: [
      "Extraordinary artistic and creative brilliance",
      "Natural glamour and attractive presence",
      "Architectural and structural thinking",
      "Attention to beauty and perfection",
      "Innovation and originality",
    ],
    weaknesses: [
      "Can be vain or overly appearance-focused",
      "Perfectionism leads to dissatisfaction",
      "May be arrogant about talents",
    ],
    luckyColors: ["Bright colors", "Multicolor", "Royal Blue"],
    luckyNumbers: [3, 7],
    luckyGems: ["Red Coral", "Carnelian"],
    luckyDays: ["Tuesday", "Friday"],
    careerPaths: ["Architecture", "Design", "Fashion", "Arts", "Jewelry"],
    compatibleNakshatras: ["Vishakha", "Anuradha", "Mrigashira", "Dhanishta"],
    lifeTheme: "Creating beauty, brilliant artistry, and the jewel of the mind",
    padaThemes: [
      { pada: 1, theme: "Virgo energy — precise artistic skill", qualities: ["Pe", "craft", "precision"] },
      { pada: 2, theme: "Virgo sub-influence — refined creativity", qualities: ["Po", "refinement", "beauty"] },
      { pada: 3, theme: "Libra sub-influence — balanced art and design", qualities: ["Ra", "harmony", "design"] },
      { pada: 4, theme: "Libra sub-influence — artistic diplomacy", qualities: ["Ri", "diplomacy", "artistry"] },
    ],
  },
  {
    nakshatraSlug: "swati",
    nakshatraName: "Swati",
    element: "Air",
    planetaryRuler: "Rahu",
    gana: "Deva",
    nature: "Chara (Movable)",
    personalities: [
      "Independent spirit with entrepreneurial instincts",
      "Diplomatically gifted and socially adept",
      "Flexible like the wind — adapts to any situation",
      "Business-minded with excellent economic sense",
      "Open-minded and receptive to new ideas",
      "Seeks freedom and self-sufficiency",
    ],
    strengths: [
      "Natural independence and entrepreneurship",
      "Diplomatic and socially gifted",
      "Flexibility and adaptability",
      "Business and economic intelligence",
      "Open-minded receptiveness",
    ],
    weaknesses: [
      "Can scatter energy too broadly",
      "May be indecisive or wavering",
      "Tendency toward restlessness",
    ],
    luckyColors: ["Blue", "Green", "Sky Blue"],
    luckyNumbers: [4, 6],
    luckyGems: ["Hessonite (Gomed)", "Blue Topaz"],
    luckyDays: ["Wednesday", "Friday"],
    careerPaths: ["Business", "Trade", "Diplomacy", "Arts", "Technology"],
    compatibleNakshatras: ["Hasta", "Uttara Phalguni", "Punarvasu", "Anuradha"],
    lifeTheme: "Independent movement, self-discovery, and diplomatic grace",
    padaThemes: [
      { pada: 1, theme: "Libra energy — diplomatic balance", qualities: ["Ru", "diplomacy", "balance"] },
      { pada: 2, theme: "Scorpio sub-influence — deep independence", qualities: ["Re", "depth", "freedom"] },
      { pada: 3, theme: "Sagittarius sub-influence — philosophical freedom", qualities: ["Ro", "philosophy", "expansion"] },
      { pada: 4, theme: "Capricorn sub-influence — disciplined enterprise", qualities: ["Ta", "discipline", "achievement"] },
    ],
  },
  {
    nakshatraSlug: "vishakha",
    nakshatraName: "Vishakha",
    element: "Fire",
    planetaryRuler: "Jupiter",
    gana: "Rakshasa",
    nature: "Mishra (Mixed)",
    personalities: [
      "Highly ambitious with laser-focused goal orientation",
      "Passionate and determined pursuer of excellence",
      "Single-minded dedication that achieves extraordinary results",
      "Competitive spirit that thrives on challenge",
      "Deep spiritual seeking alongside worldly success",
      "Powerful communicator and influencer",
    ],
    strengths: [
      "Extraordinary ambition and determination",
      "Focused goal achievement abilities",
      "Passionate pursuit of excellence",
      "Spiritual depth alongside worldly success",
      "Powerful and persuasive communication",
    ],
    weaknesses: [
      "Can be overly intense or domineering",
      "May become resentful when goals are blocked",
      "Jealousy and competitive envy",
    ],
    luckyColors: ["Orange", "Yellow", "Golden"],
    luckyNumbers: [3, 9],
    luckyGems: ["Yellow Sapphire", "Topaz"],
    luckyDays: ["Thursday", "Tuesday"],
    careerPaths: ["Politics", "Business leadership", "Sports", "Research", "Spirituality"],
    compatibleNakshatras: ["Chitra", "Anuradha", "Magha", "Rohini"],
    lifeTheme: "Triumphant pursuit, passionate achievement, and the lightning of ambition",
    padaThemes: [
      { pada: 1, theme: "Libra energy — balanced ambitious drive", qualities: ["Ti", "ambition", "balance"] },
      { pada: 2, theme: "Scorpio sub-influence — intense depth", qualities: ["Tu", "intensity", "determination"] },
      { pada: 3, theme: "Sagittarius sub-influence — philosophical fire", qualities: ["Te", "philosophy", "expansion"] },
      { pada: 4, theme: "Scorpio energy — transformative power", qualities: ["To", "transformation", "power"] },
    ],
  },
  {
    nakshatraSlug: "anuradha",
    nakshatraName: "Anuradha",
    element: "Fire",
    planetaryRuler: "Saturn",
    gana: "Deva",
    nature: "Mridu (Soft)",
    personalities: [
      "Deeply loyal and devoted in all relationships",
      "Excellent organizational and planning abilities",
      "Warm and friendly with genuine care for others",
      "Spiritually disciplined with strong values",
      "Ability to maintain deep friendships for life",
      "Natural coordinator and team builder",
    ],
    strengths: [
      "Exceptional loyalty and devotion",
      "Organizational and planning excellence",
      "Warmth and genuine friendship",
      "Spiritual discipline and values",
      "Ability to coordinate and bring people together",
    ],
    weaknesses: [
      "Can be overly self-sacrificing",
      "May feel lonely despite many friends",
      "Tendency to be too rigid in principles",
    ],
    luckyColors: ["Dark Red", "Brown", "Orange"],
    luckyNumbers: [8, 6],
    luckyGems: ["Blue Sapphire", "Dark Amethyst"],
    luckyDays: ["Saturday", "Friday"],
    careerPaths: ["Management", "Spirituality", "Counseling", "Research", "Travel"],
    compatibleNakshatras: ["Swati", "Chitra", "Vishakha", "Mula"],
    lifeTheme: "Deep friendship, devoted service, and spiritual discipline",
    padaThemes: [
      { pada: 1, theme: "Scorpio energy — deep devoted loyalty", qualities: ["Na", "loyalty", "depth"] },
      { pada: 2, theme: "Sagittarius sub-influence — philosophical devotion", qualities: ["Ni", "philosophy", "wisdom"] },
      { pada: 3, theme: "Capricorn sub-influence — disciplined organization", qualities: ["Nu", "discipline", "order"] },
      { pada: 4, theme: "Aquarius sub-influence — humanitarian service", qualities: ["Ne", "service", "humanity"] },
    ],
  },
  {
    nakshatraSlug: "jyeshtha",
    nakshatraName: "Jyeshtha",
    element: "Water/Air",
    planetaryRuler: "Mercury",
    gana: "Rakshasa",
    nature: "Tikshna (Sharp)",
    personalities: [
      "Natural authority and protective power",
      "Highly intelligent with a strategic mind",
      "Protective of those under their care",
      "Excellent at managing crises and challenges",
      "Can be eldest-born in spirit even if not in birth order",
      "Brave and willing to face difficult situations",
    ],
    strengths: [
      "Natural authority and command presence",
      "Protective and courageous",
      "Strategic intelligence",
      "Crisis management abilities",
      "Brave facing of difficult truths",
    ],
    weaknesses: [
      "Can be domineering or controlling",
      "Pride and ego can create conflicts",
      "May carry heavy burdens in isolation",
    ],
    luckyColors: ["Dark Green", "Olive", "Navy"],
    luckyNumbers: [9, 5],
    luckyGems: ["Emerald", "Peridot"],
    luckyDays: ["Wednesday", "Sunday"],
    careerPaths: ["Military", "Law", "Management", "Government", "Protection"],
    compatibleNakshatras: ["Anuradha", "Ashlesha", "Ardra", "Magha"],
    lifeTheme: "Protective authority, courageous leadership, and bearing responsibility",
    padaThemes: [
      { pada: 1, theme: "Scorpio energy — powerful authority", qualities: ["No", "authority", "power"] },
      { pada: 2, theme: "Sagittarius sub-influence — philosophical leadership", qualities: ["Ya", "wisdom", "justice"] },
      { pada: 3, theme: "Capricorn sub-influence — disciplined command", qualities: ["Yi", "discipline", "order"] },
      { pada: 4, theme: "Aquarius sub-influence — humanitarian authority", qualities: ["Yu", "service", "humanity"] },
    ],
  },
  {
    nakshatraSlug: "mula",
    nakshatraName: "Mula",
    element: "Fire",
    planetaryRuler: "Ketu",
    gana: "Rakshasa",
    nature: "Tikshna (Sharp)",
    personalities: [
      "Philosophical and investigative by nature",
      "Goes to the root of all things — seeks fundamental truth",
      "Spiritual seeker willing to question everything",
      "Strong and determined with deep inner power",
      "Research-oriented and analytical",
      "Transformation through dissolution — clears away the unnecessary",
    ],
    strengths: [
      "Deep philosophical and spiritual insight",
      "Investigative and research excellence",
      "Courage to seek fundamental truths",
      "Inner strength and determination",
      "Transformative power through wisdom",
    ],
    weaknesses: [
      "Can uproot stability in the search for truth",
      "May cause disruption in relationships",
      "Difficulty with conventional structures",
    ],
    luckyColors: ["Brown", "Dark Yellow", "Orange"],
    luckyNumbers: [7, 9],
    luckyGems: ["Cat's Eye", "Chrysoberyl"],
    luckyDays: ["Saturday", "Tuesday"],
    careerPaths: ["Research", "Philosophy", "Spirituality", "Medicine", "Investigation"],
    compatibleNakshatras: ["Ardra", "Ashlesha", "Ashwini", "Purva Ashadha"],
    lifeTheme: "Getting to the root of all things, dissolution leading to truth",
    padaThemes: [
      { pada: 1, theme: "Sagittarius energy — philosophical investigation", qualities: ["Ye", "philosophy", "truth"] },
      { pada: 2, theme: "Capricorn sub-influence — disciplined research", qualities: ["Yo", "discipline", "structure"] },
      { pada: 3, theme: "Aquarius sub-influence — humanitarian insight", qualities: ["Ba", "humanity", "vision"] },
      { pada: 4, theme: "Pisces sub-influence — spiritual depth", qualities: ["Bi", "spirituality", "depth"] },
    ],
  },
  {
    nakshatraSlug: "purva-ashadha",
    nakshatraName: "Purva Ashadha",
    element: "Water/Fire",
    planetaryRuler: "Venus",
    gana: "Manushya",
    nature: "Ugra (Fierce)",
    personalities: [
      "Invincible spirit that cannot be easily defeated",
      "Philosophical with a strong sense of justice",
      "Purifying energy that clears the path forward",
      "Energetic and enthusiastic about life",
      "Strong sense of pride and self-worth",
      "Inspiring communicator who rallies others",
    ],
    strengths: [
      "Invincible determination and resilience",
      "Strong philosophical principles",
      "Enthusiastic and energetic life force",
      "Pride and dignified self-presentation",
      "Inspiring leadership and communication",
    ],
    weaknesses: [
      "Can be arrogant or dismissive",
      "Pride may become inflexibility",
      "Tendency to take on too much",
    ],
    luckyColors: ["Cream", "White", "Pale Yellow"],
    luckyNumbers: [2, 6],
    luckyGems: ["Diamond", "White Sapphire"],
    luckyDays: ["Friday", "Thursday"],
    careerPaths: ["Law", "Philosophy", "Writing", "Arts", "Water-related professions"],
    compatibleNakshatras: ["Anuradha", "Mula", "Uttara Ashadha", "Bharani"],
    lifeTheme: "Early victory, invincible spirit, and purifying of the path",
    padaThemes: [
      { pada: 1, theme: "Sagittarius energy — philosophical victory", qualities: ["Bu", "philosophy", "victory"] },
      { pada: 2, theme: "Capricorn sub-influence — disciplined triumph", qualities: ["Dha", "discipline", "achievement"] },
      { pada: 3, theme: "Aquarius sub-influence — humanitarian pride", qualities: ["Bha", "vision", "service"] },
      { pada: 4, theme: "Pisces sub-influence — spiritual invincibility", qualities: ["Fa", "spirit", "depth"] },
    ],
  },
  {
    nakshatraSlug: "uttara-ashadha",
    nakshatraName: "Uttara Ashadha",
    element: "Earth/Fire",
    planetaryRuler: "Sun",
    gana: "Manushya",
    nature: "Sthira (Fixed)",
    personalities: [
      "Unstoppably righteous and principled",
      "Achieves lasting victory through virtue",
      "Sincere and genuine in all dealings",
      "Persistent in the face of all obstacles",
      "Universal in perspective — serves all of humanity",
      "Steady and reliable with deep integrity",
    ],
    strengths: [
      "Righteous principles and deep integrity",
      "Persistent long-term achievement",
      "Universal service orientation",
      "Sincerity and genuineness",
      "Lasting success through virtue",
    ],
    weaknesses: [
      "Can be overly rigid in principles",
      "May be taken advantage of due to honesty",
      "Difficulty accepting compromise",
    ],
    luckyColors: ["Gold", "Copper", "Yellow"],
    luckyNumbers: [1, 8],
    luckyGems: ["Ruby", "Gold"],
    luckyDays: ["Sunday", "Saturday"],
    careerPaths: ["Government", "Military", "Governance", "Philosophy", "Social reform"],
    compatibleNakshatras: ["Rohini", "Pushya", "Shravana", "Bharani"],
    lifeTheme: "Ultimate victory through righteousness and lasting achievement",
    padaThemes: [
      { pada: 1, theme: "Sagittarius energy — righteous philosophy", qualities: ["Be", "righteousness", "principle"] },
      { pada: 2, theme: "Capricorn energy — disciplined victory", qualities: ["Bo", "persistence", "achievement"] },
      { pada: 3, theme: "Capricorn sub-influence — structured success", qualities: ["Ja", "structure", "success"] },
      { pada: 4, theme: "Capricorn sub-influence — disciplined integrity", qualities: ["Ji", "integrity", "order"] },
    ],
  },
  {
    nakshatraSlug: "shravana",
    nakshatraName: "Shravana",
    element: "Air",
    planetaryRuler: "Moon",
    gana: "Deva",
    nature: "Chara (Movable)",
    personalities: [
      "Exceptional listener and absorber of knowledge",
      "Deeply learned and committed to education",
      "Excellent communicator who spreads wisdom",
      "Organized and meticulous in approach",
      "Connection to Vishnu's preserving energy",
      "Skilled at synthesizing and sharing information",
    ],
    strengths: [
      "Extraordinary listening and learning ability",
      "Deep knowledge and wisdom",
      "Excellent communication and teaching",
      "Organizational precision",
      "Ability to preserve and transmit knowledge",
    ],
    weaknesses: [
      "Can be overly orthodox or traditional",
      "May struggle with gossip",
      "Tendency toward over-sensitivity",
    ],
    luckyColors: ["Blue", "Navy", "White"],
    luckyNumbers: [2, 7],
    luckyGems: ["Pearl", "Moonstone"],
    luckyDays: ["Monday", "Thursday"],
    careerPaths: ["Education", "Media", "Communication", "Research", "Counseling"],
    compatibleNakshatras: ["Rohini", "Pushya", "Hasta", "Revati"],
    lifeTheme: "Listening, learning, preserving and sharing sacred knowledge",
    padaThemes: [
      { pada: 1, theme: "Capricorn energy — disciplined learning", qualities: ["Ju", "learning", "discipline"] },
      { pada: 2, theme: "Aquarius sub-influence — humanitarian knowledge", qualities: ["Je", "vision", "sharing"] },
      { pada: 3, theme: "Pisces sub-influence — intuitive wisdom", qualities: ["Jo", "intuition", "spirituality"] },
      { pada: 4, theme: "Aries sub-influence — active communication", qualities: ["Gha", "action", "leadership"] },
    ],
  },
  {
    nakshatraSlug: "dhanishta",
    nakshatraName: "Dhanishta",
    element: "Air/Fire",
    planetaryRuler: "Mars",
    gana: "Rakshasa",
    nature: "Chara (Movable)",
    personalities: [
      "Musical and rhythmically gifted",
      "Socially adaptable and versatile",
      "Naturally attracts wealth and abundance",
      "Ambitious with good organizational abilities",
      "Active and dynamic with many interests",
      "Charitable and generous with material resources",
    ],
    strengths: [
      "Musical talent and rhythmic sensitivity",
      "Social adaptability and versatility",
      "Natural ability to attract wealth",
      "Ambitious drive and organizational skill",
      "Charitable generosity",
    ],
    weaknesses: [
      "Can be boastful or ostentatious",
      "May be materialistic",
      "Tendency toward impatience",
    ],
    luckyColors: ["Silver", "Gold", "Blue-Green"],
    luckyNumbers: [8, 3],
    luckyGems: ["Red Coral", "Carnelian"],
    luckyDays: ["Tuesday", "Saturday"],
    careerPaths: ["Music", "Business", "Finance", "Dance", "Technology"],
    compatibleNakshatras: ["Chitra", "Swati", "Revati", "Shravana"],
    lifeTheme: "Musical abundance, social prosperity, and rhythmic success",
    padaThemes: [
      { pada: 1, theme: "Capricorn energy — disciplined wealth creation", qualities: ["Ga", "discipline", "wealth"] },
      { pada: 2, theme: "Capricorn sub-influence — organized abundance", qualities: ["Gi", "organization", "prosperity"] },
      { pada: 3, theme: "Aquarius energy — humanitarian prosperity", qualities: ["Gu", "vision", "generosity"] },
      { pada: 4, theme: "Aquarius sub-influence — innovative success", qualities: ["Ge", "innovation", "freedom"] },
    ],
  },
  {
    nakshatraSlug: "shatabhisha",
    nakshatraName: "Shatabhisha",
    element: "Water/Air",
    planetaryRuler: "Rahu",
    gana: "Rakshasa",
    nature: "Chara (Movable)",
    personalities: [
      "Healer with mystical and unconventional gifts",
      "Independent thinker who challenges conventions",
      "Deep researcher and truth seeker",
      "Visionary who sees beyond the obvious",
      "Reclusive at times, needing solitude for insight",
      "Strong sense of cosmic law and ethics",
    ],
    strengths: [
      "Extraordinary healing and research abilities",
      "Visionary and innovative thinking",
      "Independence and self-sufficiency",
      "Deep investigation of hidden truths",
      "Connection to cosmic law and principles",
    ],
    weaknesses: [
      "Can be secretive or isolated",
      "May be perceived as eccentric",
      "Tendency to be obstinate in views",
    ],
    luckyColors: ["Blue", "Electric Blue", "Navy"],
    luckyNumbers: [4, 8],
    luckyGems: ["Hessonite (Gomed)", "Blue Sapphire"],
    luckyDays: ["Saturday", "Wednesday"],
    careerPaths: ["Medicine", "Research", "Astrology", "Technology", "Healing arts"],
    compatibleNakshatras: ["Ardra", "Uttara Bhadrapada", "Ashwini", "Purva Bhadrapada"],
    lifeTheme: "Hidden healing, cosmic truth-seeking, and unconventional wisdom",
    padaThemes: [
      { pada: 1, theme: "Aquarius energy — visionary healing", qualities: ["Go", "vision", "healing"] },
      { pada: 2, theme: "Pisces sub-influence — mystical research", qualities: ["Sa", "mysticism", "depth"] },
      { pada: 3, theme: "Aries sub-influence — pioneering healing", qualities: ["Si", "initiative", "healing"] },
      { pada: 4, theme: "Taurus sub-influence — practical mysticism", qualities: ["Su", "practical", "grounded"] },
    ],
  },
  {
    nakshatraSlug: "purva-bhadrapada",
    nakshatraName: "Purva Bhadrapada",
    element: "Fire/Air",
    planetaryRuler: "Jupiter",
    gana: "Manushya",
    nature: "Ugra (Fierce)",
    personalities: [
      "Intensely passionate and idealistic",
      "Spiritually inclined with transformative energy",
      "Fierce defender of principles and beliefs",
      "Unconventional and radical in thinking",
      "Deep emotional life with extremes of experience",
      "Visionary who sees two worlds simultaneously",
    ],
    strengths: [
      "Intense spiritual passion and depth",
      "Transformative power through idealism",
      "Unconventional brilliance",
      "Deep emotional understanding",
      "Visionary spiritual insight",
    ],
    weaknesses: [
      "Can swing between extremes",
      "May be impractical in idealism",
      "Intensity can be overwhelming",
    ],
    luckyColors: ["Purple", "Indigo", "Dark Blue"],
    luckyNumbers: [3, 9],
    luckyGems: ["Yellow Sapphire", "Amethyst"],
    luckyDays: ["Thursday", "Tuesday"],
    careerPaths: ["Spirituality", "Philosophy", "Psychology", "Research", "Arts"],
    compatibleNakshatras: ["Uttara Bhadrapada", "Ardra", "Ashlesha", "Shatabhisha"],
    lifeTheme: "Passionate spirituality, transformative fire, and visionary idealism",
    padaThemes: [
      { pada: 1, theme: "Aquarius energy — visionary passion", qualities: ["Se", "vision", "passion"] },
      { pada: 2, theme: "Pisces sub-influence — spiritual intensity", qualities: ["So", "spirituality", "depth"] },
      { pada: 3, theme: "Aries sub-influence — fiery idealism", qualities: ["Da", "fire", "idealism"] },
      { pada: 4, theme: "Taurus sub-influence — grounded transformation", qualities: ["Di", "stability", "transformation"] },
    ],
  },
  {
    nakshatraSlug: "uttara-bhadrapada",
    nakshatraName: "Uttara Bhadrapada",
    element: "Water/Fire",
    planetaryRuler: "Saturn",
    gana: "Manushya",
    nature: "Sthira (Fixed)",
    personalities: [
      "Deeply wise with profound philosophical insight",
      "Compassionate and philanthropic beyond measure",
      "Stable and steady in turbulent waters of life",
      "Spiritual master energy — teacher of teachers",
      "Abundance flows naturally to and through them",
      "Ability to see the deep currents of existence",
    ],
    strengths: [
      "Profound wisdom and philosophical depth",
      "Deep compassion and philanthropic heart",
      "Stability and steady guidance",
      "Spiritual mastery and teaching",
      "Natural abundance and generosity",
    ],
    weaknesses: [
      "Can be slow or overly cautious",
      "May withdraw from the world excessively",
      "Tendency toward indolence",
    ],
    luckyColors: ["Blue", "Black", "Indigo"],
    luckyNumbers: [8, 7],
    luckyGems: ["Blue Sapphire", "Lapis Lazuli"],
    luckyDays: ["Saturday", "Thursday"],
    careerPaths: ["Spirituality", "Teaching", "Philosophy", "Charity", "Deep research"],
    compatibleNakshatras: ["Purva Bhadrapada", "Revati", "Shravana", "Pushya"],
    lifeTheme: "Deep wisdom, compassionate service, and spiritual abundance",
    padaThemes: [
      { pada: 1, theme: "Pisces energy — deep spiritual wisdom", qualities: ["Du", "wisdom", "spirituality"] },
      { pada: 2, theme: "Aries sub-influence — active compassion", qualities: ["Tha", "initiative", "service"] },
      { pada: 3, theme: "Taurus sub-influence — stable abundance", qualities: ["Jha", "stability", "abundance"] },
      { pada: 4, theme: "Gemini sub-influence — communicative wisdom", qualities: ["Da", "teaching", "communication"] },
    ],
  },
  {
    nakshatraSlug: "revati",
    nakshatraName: "Revati",
    element: "Water/Earth",
    planetaryRuler: "Mercury",
    gana: "Deva",
    nature: "Mridu (Soft)",
    personalities: [
      "Spiritually advanced with natural grace",
      "Nurturing and creative with abundant gifts",
      "Completing energy — brings things to beautiful fruition",
      "Deeply compassionate and caring for all beings",
      "Connected to both material and spiritual prosperity",
      "Artistic and emotionally sensitive",
    ],
    strengths: [
      "Spiritual advancement and natural grace",
      "Nurturing and abundant generosity",
      "Creative completion and bringing things to fruition",
      "Deep compassion for all living beings",
      "Connection to prosperity and artistic beauty",
    ],
    weaknesses: [
      "Can be overly sensitive or emotional",
      "May be naive or idealistic",
      "Tendency toward escapism",
    ],
    luckyColors: ["White", "Cream", "Silver"],
    luckyNumbers: [5, 2],
    luckyGems: ["Emerald", "Pearl"],
    luckyDays: ["Wednesday", "Monday"],
    careerPaths: ["Arts", "Spirituality", "Social work", "Music", "Healing"],
    compatibleNakshatras: ["Uttara Bhadrapada", "Dhanishta", "Pushya", "Mrigashira"],
    lifeTheme: "Spiritual completion, abundant grace, and compassionate completion",
    padaThemes: [
      { pada: 1, theme: "Pisces energy — spiritual nurturing", qualities: ["De", "nurturing", "grace"] },
      { pada: 2, theme: "Aries sub-influence — active spiritual energy", qualities: ["Do", "initiative", "spirituality"] },
      { pada: 3, theme: "Taurus sub-influence — material-spiritual abundance", qualities: ["Cha", "abundance", "beauty"] },
      { pada: 4, theme: "Gemini sub-influence — communication and completion", qualities: ["Chi", "expression", "completion"] },
    ],
  },
];

export function getNakshatraPersonality(slug: string): NakshatraPersonality | undefined {
  return NAKSHATRA_PERSONALITIES.find((p) => p.nakshatraSlug === slug);
}

/**
 * Get nakshatra personality for a specific pada.
 */
export function getPadaTheme(
  slug: string,
  pada: number
): NakshatraPersonality["padaThemes"][0] | undefined {
  const personality = getNakshatraPersonality(slug);
  return personality?.padaThemes.find((p) => p.pada === pada);
}

// Re-export NAKSHATRAS for easy access
export { NAKSHATRAS } from "@/data/nakshatras";
export { NAKSHATRA_DATA, getNakshatraBySlug } from "@/lib/nakshatraData";
